name: Build Executable

on:
    push:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Install Conan
              run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade conan
            - name: Setup Conan
              run: |
                  conan profile detect
                  if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
                      sudo apt-get update
                      sudo apt-get install gcc g++ -y
                  fi
              shell: bash
            - name: Create Build Directory
              run: mkdir -p build
            - name: Build Project
              run: |
                  cd build
                  if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
                      cmake -DCMAKE_BUILD_TYPE=Debug ..
                      cmake --build .
                  elif [ "${{ matrix.os }}" == "windows-latest" ]; then
                      cmake .. -DCMAKE_BUILD_TYPE=Debug 
                      cmake --build .
                  fi
              shell: bash
