name: Release Artifacts

on:
  workflow_run:
    workflows: ["Build Executable"]
    types:
      - completed
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Display structure of downloaded files
        run: ls -R artifacts
        shell: bash
        
      - name: Create release tag
        id: create_tag
        run: |
          UNIQUE_CODE=$(openssl rand -hex 3)
          TAG_NAME="Releases-${UNIQUE_CODE}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag_name=${UNIQUE_CODE}" >> $GITHUB_OUTPUT
        
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Releases-${{ steps.create_tag.outputs.tag_name }}
          name: Release ${{ steps.create_tag.outputs.tag_name }}
          files: artifacts/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}